### ISSUE TITLE
Do not import same package

### ISSUE THREAD

**Issue by hsh2001** [Tom-xacademy/xa-snippets#3]
![화면-기록-2020-05-20-오후-1 40 07](https://user-images.githubusercontent.com/32220765/82405749-bc6da000-9a9f-11ea-8c3f-a32a4424a93d.gif)

`React` is re-imported!!

**Comment by Tom-xacademy** [comment]
As far as I know, VSCode doesn't allow excluding one line if they exist or something like that so this is impossible to implement. The most I could do is to remove the react import from the component-type snippets and then you could simply type 'imr' at the top.

But honestly speaking, I don't see the point of it. I think it's bad practise to put two components in the same file and if you avoid that, you won't end up with double imports. I also find it more convenient that I don't have to go to the top and type 'imr' every time.

**Comment by hsh2001** [comment]
I agree with you. But sometimes we need multiple components in a single file when the code of the component is very short or related with some component. Then we'd better not move it to another file. Then why don't you make a new snippet without `import` and `export`?

e.g.:
```jsx
const SomeComponent: React.FC = () => {
  return (
    <div>

    <div>
  );
}
```

**Comment by Tom-xacademy** [comment]
Added in v2.5.0 as sfcnie and pfcnie.

sfcnie => simple function component with its own interface but no import and export.
pfcnie => propless function component without interface, export, and import.

**Comment by hsh2001** [comment]
Thanks. You saved my keyboard.
